baseURL: 'https://jdxj.github.io'
title: 'jdxj'
theme: "PaperMod"
publishDir: "docs"
buildDrafts: true
enableEmoji: true
enableGitInfo: true
hasCJKLanguage: true
watch: true
pluralizeListTitles: false
googleAnalytics: G-FBE4H074FW
