baseURL: 'https://jdxj.github.io'
title: 'jdxj'
theme: "PaperMod"
publishdir: "docs"

params:
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowBreadCrumbs: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  showtoc: true
  tocopen: true