main:
  - identifier: archives
    name: Archives
    url: /archives
  - identifier: collections
    name: Collections
    url: /posts
  - identifier: search
    name: Search
    url: /search
  - identifier: tags
    name: Tags
    url: /tags
