baseURL: "https://jdxj.github.io/"
languageCode: "en-us"
title: "绝顶相机"
theme: "eclectic"
publishdir: "docs"

author:
  name: "jdxj"
  location: "China"
  hours: "**Mon-Fri:** 9:00AM - 6:00PM, ET"

menu:
  main:
    - identifier: about
      name: About
      url: /about
      weight: 100

params:
  color: "#4f46e5"
  copyright: "Copyright &copy; 2022 jdxj.
    All Rights Reserved."
  footer:
    - title: About
      content: >
        Hello World!.
    - title: Recent Blog Posts
      recents: posts
      recentCount: 3
